Add Systemd config for self-hosted server
atuinsh/docs pull request #45
Opened 2024-03-14 04:29 UTC by svenstaro

Part of https://github.com/atuinsh/atuin/issues/1864.

2024-04-29 08:06 UTC, ellie requested changes

2024-05-26 00:41 UTC, svenstaro commented on src/content/docs/self-hosting/systemd.mdx
> +Setting up Atuin with Systemd directly has the benefit of being the conceptually simplest of
I reworded this to sound less suggestive.

2024-05-26 00:41 UTC, svenstaro commented
Along with my changes in #1879, this should be good to go.

2024-05-26 07:22 UTC, ellie commented on src/content/docs/self-hosting/systemd.mdx
> +Setting up Atuin with Systemd directly has the benefit of being the conceptually simplest of
The entire section about distro package managers _may_ be true at some point in the future, but is not presently true, and depends entirely on package maintainers. I'll stand by my prior comment asking for its removal :)

2024-05-27 06:29 UTC, svenstaro commented on src/content/docs/self-hosting/systemd.mdx
> +Setting up Atuin with Systemd directly has the benefit of being the conceptually simplest of
Ok, it's gone now.

2024-06-03 10:20 UTC, ellie approved these changes
Thank you!

2024-06-03 10:21 UTC, ellie commented
Ah wait just one more

Could you add this page to the sidebar please?

https://github.com/atuinsh/docs/blob/828e88c1e388585a11e693988567221eeebf7019/astro.config.mjs#L62-L67

2024-06-04 15:03 UTC, svenstaro commented
Done!

2024-06-04 15:49 UTC, ellie approved these changes
Great! Thanks for the work 🥳

2024-06-04 15:49 UTC, merged